### This workflow can be run manually from Actions tab in your repository by selecting the "Create Release" workflow.
### When your project is ready for releases, you should:
###   - Uncomment the `schedule` section to run this workflow automatically on a schedule.
###     - As written, this workflow will run every Sunday at midnight UTC.
###   - Remove the `draft: true` line from the `Create Release` step to publish the release immediately.
# TODO: QC/Validation (ex. 0 rows)

name: Create Release

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 * * 0'

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install Dependencies
        run: poetry install --no-interaction

      - name: Run Transform
        run: |
          make run
          poetry run python scripts/generate-rdf.py

      - name: Get Date for Release Tag
        run: echo "DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV

      # Further customization for this action is available. See:
      # https://github.com/softprops/action-gh-release/?tab=readme-ov-file#-customizing
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.DATE }}
          files: |
            output/*
          generate_release_notes: true
          draft: true