# This GitHub Action updates the documentation with information about the latest KG build/release.

name: Update Documentation

on:
  workflow_run:
    workflows: ["Create Release"]
    types:
      - completed

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install Dependencies
        run: |
          poetry install --with dev --no-interaction

      - name: Build Documentation
        run: |
          poetry run python scripts/get-latest-report.py
          make docs

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: site
          target-folder: docs
          clean: true
